### ISSUE TITLE
Including grumpy causes java.lang.NoSuchMethodError: com.google.common.base.Platform.systemNanoTime()J

### ISSUE THREAD

**Issue by atulkgupta9** [davidmoten/grumpy#3]
I am using ` <dependency>
            <groupId>com.github.davidmoten</groupId>
            <artifactId>grumpy-ogc</artifactId>
            <version>0.2.2</version>
        </dependency>`. It is giving me `java.lang.NoSuchMethodError: com.google.common.base.Platform.systemNanoTime()J` while running the application. I searched and got no solution to this problem. Please help.

**Comment by davidmoten** [comment]
I think grumpy-projection depends on an old guava and you likely have a later version present. I'll update with latest guava and rerelease soon.

**Comment by atulkgupta9** [comment]
I have following two dependencies in my pom file 
```
 <dependency>
            <groupId>com.github.davidmoten</groupId>
            <artifactId>grumpy-ogc</artifactId>
            <version>0.2.2</version>
        </dependency>

        <dependency>
            <groupId>com.github.davidmoten</groupId>
            <artifactId>rtree</artifactId>
            <version>0.8-RC10</version>
        </dependency>
```

Grumpy is needed for rtree, that's why I included it. Can you please let me know if I can do something to solve it.

**Comment by davidmoten** [comment]
I'm making a fix now for this but there is a workaround. Exclude the *guava-base* artifact from *grumpy-ogc* because you have *guava* on the classpath already.

This is how you exclude an artifact with maven:

```xml
    <dependency>
      <groupId>sample.ProjectA</groupId>
      <artifactId>Project-A</artifactId>
      <version>1.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>  <!-- declare the exclusion here -->
          <groupId>sample.ProjectB</groupId>
          <artifactId>Project-B</artifactId>
        </exclusion>
      </exclusions> 
    </dependency>
```

**Comment by davidmoten** [comment]
@atulkgupta9 [v2.4.0](https://github.com/davidmoten/grumpy/releases/tag/0.2.4) is on Maven Central now and excludes *guava-base* dependency. If you use that you shouldn't need the maven exclusion anymore.
